# app block
FROM node:18.15.0 as nodework
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
COPY . .
ENV NODE_ENV production

ARG VITE_STRAPI_API_TOKEN
ENV VITE_STRAPI_API_TOKEN=$VITE_STRAPI_API_TOKEN

ARG VITE_STRAPI_API_ROOT
ENV VITE_STRAPI_API_ROOT=$VITE_STRAPI_API_ROOT

ARG VITE_STRAPI_COMPONENT_URL
ENV VITE_STRAPI_COMPONENT_URL=$VITE_STRAPI_COMPONENT_URL

ARG VITE_STRAPI_COMPONENT_CONFIG_URL
ENV VITE_STRAPI_COMPONENT_CONFIG_URL=$VITE_STRAPI_COMPONENT_CONFIG_URL

ARG VITE_STRAPI_CONTENT_TYPE
ENV VITE_STRAPI_CONTENT_TYPE=$VITE_STRAPI_CONTENT_TYPE

ARG VITE_STRAPI_COMPONENT_DATA_URL
ENV VITE_STRAPI_COMPONENT_DATA_URL=$VITE_STRAPI_COMPONENT_DATA_URL

RUN npm run build

# nginx block
FROM nginx:1.23-alpine
COPY nginx.conf /etc/nginx/nginx.conf 
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=nodework /app/dist .

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]